module.exports = {
  purge: false,
  theme: {
    extend: {
      fontSize: {
        xxs: ".5rem",
        xs: ".75rem",
        sm: ".875rem",
        tiny: ".875rem",
      },
      borderRadius: {
        "20": "20px",
      },
    },

    //   colors: {
    //     // background-color: #7289da !important;
    //     // color: white !important;
    //     "discord-1": "#7289da",
    //     "discord-2": "white",
    //     "afr-1": "#DC9DC7",
    //     "afr-2": "#776E3F",
    //     "artistforreal-1": "#776E3F",
    //     "artistforreal-2": "#DC9DC7",
    //     "artistforreal-text": "white",
    //     "connect-1": "#FEC8BE",
    //     "connect-2": "#20AD65",
    //     "interview-1": "black",
    //     "interview-2": "white",
    //     //
    //     "features-1": "#A9C0FE",
    //     "features-2": "#FE5E22",
    //     "lexicon-1": "#A9C0FE",
    //     "lexicon-2": "#FE5E22",
    //     //
    //     "meetup-1": "#FCBF29",
    //     //PURPLE
    //     "meetup-2": "#6B20E0",
    //     "meetup-purple-100": "#E9D2FD",
    //     "meetup-purple-200": "#D1A5FB",
    //     "meetup-purple-300": "#B277F5",
    //     "meetup-purple-400": "#9554EC",
    //     "meetup-purple-500": "#6B20E0",
    //     "meetup-purple-600": "#5217C0",
    //     "meetup-purple-700": "#3D10A1",
    //     "meetup-purple-800": "#2A0A81",
    //     "meetup-purple-900": "#1D066B",
    //     "takeover-1": "#CFD3BD",
    //     "takeover-2": "#ED512C",
    //     "takeover-text": "black",
    //     "talks-1": "#7DE0E6",
    //     "talks-2": "#FF2A93",
    //     "conference-1": "#75FFC0",
    //     "conference-2": "#7B30CF",
    //     "hyperlink-1": "#F3F0E9",
    //   },
    //   spacing: {
    //     28: "7rem",
    //   },
    //   letterSpacing: {
    //     tighter: "-.04em",
    //   },
    //   lineHeight: {
    //     tight: 1.2,
    //   },
    //   width: {
    //     content: "1000px",
    //   },
    //   height: {
    //     sm: "8px",
    //     md: "16px",
    //     lg: "24px",
    //     xl: "600px",
    //   },
    //   maxHeight: {
    //     sm: "8px",
    //     md: "16px",
    //     lg: "380px",
    //     xl: "600px",
    //   },
    //   fontSize: {
    //     xxs: ".5rem",
    //     xs: ".75rem",
    //     sm: ".875rem",
    //     tiny: ".875rem",
    //     base: "1rem",
    //     lg: "1.125rem",
    //     xl: "1.25rem",
    //     "2xl": "1.5rem",
    //     "3xl": "1.875rem",
    //     "4xl": "2.25rem",
    //     "5xl": "3rem",
    //     "6xl": "4rem",
    //     "7xl": "5rem",
    //     "8xl": "6rem",
    //     "9xl": "7rem",
    //     "10xl": "8rem",
    //   },
    //   boxShadow: {
    //     small: "0 5px 10px rgba(0, 0, 0, 0.12)",
    //     medium: "0 8px 30px rgba(0, 0, 0, 0.12)",
    //   },
    //   borderWidth: {
    //     "1": "1px",
    //     "0": "0",
    //     "2": "2px",
    //     "4": "4px",
    //     "6": "6px",
    //     "8": "8px",
    //   },
    // },
  },
  variants: {},
  plugins: [],
  corePlugins: {},
};
