backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: public/images
public_folder: /images

collections:
  - name: compositions
    label: Compositions
    label_singular: "Composition"
    folder: content/compositions
    create: true
    slug: "{{name}}"
    media_folder: /public/images
    public_folder: /images
    path: "{{slug}}/index"
    fields:
      - label: "_type"
        name: "_type"
        widget: "hidden"
        default: "composition"
      - label: Slug
        name: slug
        widget: string
      - label: Name
        name: name
        widget: string
      - label: Description
        name: description
        widget: text
      - label: "Photo"
        name: "photo"
        widget: "image"
      - label: Compositors
        name: "compositors"
        widget: "relation"
        multiple: true
        collection: "composers"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]
      - label: "Instructions"
        name: "instructions"
        widget: "markdown"

  - name: composers
    label: Composers
    label_singular: "Composer"
    folder: content/composers
    create: true
    slug: "{{name}}"
    media_folder: /public/images
    public_folder: /images
    fields:
      - label: "_type"
        name: "_type"
        widget: "hidden"
        default: "composers"
      - label: Slug
        name: slug
        widget: string
      - label: Name
        name: name
        widget: string
      - label: "Photo"
        name: "photo"
        widget: "image"
      - label: Country
        name: country
        widget: string
      - label: Website
        name: website
        widget: string
      - label: Biography
        name: biography
        widget: text
