backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: composers
    label: Composers
    label_singular: "Composer"
    folder: content/composers
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - label: Name
        name: name
        widget: string
      - label: "Photo"
        name: "photo"
        widget: "image"
      - label: Country
        name: country
        widget: string
      - label: Website
        name: website
        widget: string
      - label: Biography
        name: biography
        widget: text
